# Thanks for downloading ArathiBasin! #
#==============================#

# If you want to use permissions with ArathiBasin, you must set this to true #
usePermissions: false

blueTeamName: "Alliance"
redTeamName: "Horde"

minTeamSize: 5
maxTeamSize: 15

startWait: 120
endWait: 120

scoreWarning: 1400
scoreWin: 1600